package db;


import java.sql.*;

/**
 * Base class for database access
 */
public abstract class ADatabaseAccess implements DatabaseAccess {
    protected Connection _connection = null;

    /**
     * Connect to database
     */
    public abstract void connect() throws SQLException;

    public ResultSet query(PreparedStatement statement) throws SQLException {
        checkDb();
        var resultSet = statement.executeQuery();
        return resultSet;
    }

    public int update(PreparedStatement statement) throws SQLException {
        checkDb();
        var result = statement.executeUpdate();
        statement.close();

        return result;
    }

    public ResultSet insert(PreparedStatement statement) throws Exception {
        checkDb();
        var count = statement.executeUpdate();

        if (count == 0) {
            throw new Exception("Insert statement failed.");
        } else {
            return statement.getGeneratedKeys();
        }
    }

    public void close() {
        try {
            if (_connection != null && !_connection.isClosed()) {
                _connection.close();
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkDb();
        return _connection.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        checkDb();
        return _connection.prepareStatement(sql, autoGeneratedKeys);
    }

    private void checkDb() throws SQLException {
        if (_connection == null || _connection.isClosed()) {
            connect();
        }
    }
}
