package db;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public interface DatabaseAccess {

    /**
     * Connect to database
     * @throws SQLException
     */
    void connect() throws SQLException;

    /**
     * query with result
     * @param statement
     * @return
     * @throws SQLException
     */
    ResultSet query(PreparedStatement statement) throws SQLException;

    /**
     * Update query for database
     * @param statement
     * @return
     * @throws SQLException
     */
    int update(PreparedStatement statement) throws SQLException;

    /**
     * Insert query for database
     * @param statement
     * @return
     * @throws SQLException
     */
    ResultSet insert(PreparedStatement statement) throws Exception;

    /**
     * Close the connection
     */
    void close();

    /**
     * Returns a prepared statement for the given SQL string
     * @param sql
     * @return
     */
    PreparedStatement prepareStatement(String sql) throws SQLException;

    /**
     * Returns a prepared statement for the given SQL string
     * option to generate auto generated keys for insert statements
     * @param sql
     * @return
     */
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
}
